from models import db, Unidad
from app import app

# Lista de nombres de UNIDAD (exactamente como la enviaste)
unidades = [
    "CALIDAD DE VIDA-AUSENTISMO POR LICENCIAS MÉDICAS",
    "CALIDAD DE VIDA-BIENESTAR",
    "CALIDAD DE VIDA-DISPOSITIVOS INFANTILES",
    "CALIDAD DE VIDA-CLÍNICA DEL FUNCIONARIO",
    "CALIDAD DE VIDA-FUNCIONARIOS DAMNIFICADOS POR EL INCENDIO DE FEBRERO DE 2024",
    "PERSONAL-LICENCIAS MÉDICAS",
    "PERSONAL-HONORARIOS",
    "PERSONAL-COMISIONES DE SERVICIO",
    "PERSONAL-PROPUESTAS",
    "PERSONAL-CONTROL DE ASISTENCIA",
    "PERSONAL-ASIGANCIONES",
    "ESTUDIOS Y DESARROLLO ORGANIZACIONAL-PROCESO DE SELECCIÓN (INTERNOS - EXTERNOS)",
    "ESTUDIOS Y DESARROLLO ORGANIZACIONAL-PROCESOS DE NORMALIZACIÓN",
    "ESTUDIOS Y DESARROLLO ORGANIZACIONAL-RECLUTAMIENTO DE FUNCIONARIOS TRANSITORIOS",
    "ESTUDIOS Y DESARROLLO ORGANIZACIONAL-CAMBIOS DE SERVICIO",
    "ESTUDIOS Y DESARROLLO ORGANIZACIONAL-CAPACITACIÓN",
    "ESTUDIOS Y DESARROLLO ORGANIZACIONAL-PERFILES DE CARGO",
    "CONCILIACION Y TRATO-ATENCIONES INDIVIDUALES",
    "CONCILIACION Y TRATO-ATENCIONES GRUPALES",
    "CONCILIACION Y TRATO-MEDIACIONES",
    "CONCILIACION Y TRATO-CONCILIACIONES",
    "CONCILIACION Y TRATO-REUNIONES DE COORDINACIÓN",
    "REMUNERACIONES-LIQUIDACIONES DE SUELDO",
    "REMUNERACIONES-REMUNERACIONES",
    "REMUNERACIONES-HORAS EXTRAORDONARIAS",
    "REMUNERACIONES-REINTEGROS",
    "REMUNERACIONES-RETENCIONES JUDICIALES",
    "REMUNERACIONES-PARTICIPACIÓN GREMIAL",
    "HIGIENE Y SEGURIDAD-TRABAJO PESADO",
    "HIGIENE Y SEGURIDAD-SIMULACROS",
    "HIGIENE Y SEGURIDAD-TASAS",
    "HIGIENE Y SEGURIDAD-ENFERMEDADES PROFESIONALES",
    "HIGIENE Y SEGURIDAD-REGLAMENTO INTERNO",
    "HIGIENE Y SEGURIDAD-FORMULARIOS DE AGRESIÓN A FUNCIONARIOS",
    "HIGIENE Y SEGURIDAD-TRASTORNOS MUSCULOESQUELÉTICOS RELACIONADOS AL TRABAJO",
    "HIGIENE Y SEGURIDAD-CEAL -  SM",
    "HIGIENE Y SEGURIDAD-COGRID",
    "CONTROL DE PERSONAS-DOTACIÓN AUTORIZADAS RESOLUCIÓN DE PRESUPUESTO DEL SSVQ 2025",
    "CONTROL DE PERSONAS-DOTACIÓN EFECTIVA",
    "CONTROL DE PERSONAS-RESPALDOS POR BRECHA",
    "CONTROL DE PERSONAS-RESPALDOS POR FUEROS MATERNALES",
    "CONTROL DE PERSONAS-SOLICITUDES DE TRANSPARENCIAS SUBDIRECCIÓN",
    "CONTROL DE PERSONAS-RECLAMOS POR VULNERACIÓN DE DERECHOS PRESENTADOS  A LA CONTRALORÍA, POR TEMAS RELACIONADOS  GESTIÓN DE PERSONAS"
]

with app.app_context():
    creadas = 0
    for nombre in unidades:
        nombre = nombre.strip()
        # Verifica si ya existe (evita duplicados)
        if not Unidad.query.filter_by(nombre=nombre).first():
            nueva = Unidad(nombre=nombre)
            db.session.add(nueva)
            creadas += 1
    db.session.commit()
    print(f"Unidades creadas: {creadas}")
