from models import db, Usuario, Unidad
from app import app

# Cada usuario: USUARIO, PASSWORD, ROL, ACTIVO, UNIDAD (nombre exacto de la unidad)
usuarios = [
    ("CALIDAD DE VIDA5", "1234", "USUARIO", True, "CALIDAD DE VIDA-AUSENTISMO POR LICENCIAS MÉDICAS"),
    ("CALIDAD DE VIDA4", "1234", "USUARIO", True, "CALIDAD DE VIDA-BIENESTAR"),
    ("CALIDAD DE VIDA3", "1234", "USUARIO", True, "CALIDAD DE VIDA-DISPOSITIVOS INFANTILES"),
    ("CALIDAD DE VIDA2", "1234", "USUARIO", True, "CALIDAD DE VIDA-CLÍNICA DEL FUNCIONARIO"),
    ("CALIDAD DE VIDA1", "1234", "USUARIO", True, "CALIDAD DE VIDA-FUNCIONARIOS DAMNIFICADOS POR EL INCENDIO DE FEBRERO DE 2024"),
    ("PERSONAL6", "1234", "USUARIO", True, "PERSONAL-LICENCIAS MÉDICAS"),
    ("PERSONAL5", "1234", "USUARIO", True, "PERSONAL-HONORARIOS"),
    ("PERSONAL4", "1234", "USUARIO", True, "PERSONAL-COMISIONES DE SERVICIO"),
    ("PERSONAL3", "1234", "USUARIO", True, "PERSONAL-PROPUESTAS"),
    ("PERSONAL2", "1234", "USUARIO", True, "PERSONAL-CONTROL DE ASISTENCIA"),
    ("PERSONAL1", "1234", "USUARIO", True, "PERSONAL-ASIGANCIONES"),
    ("ESTUDIOS Y DESARROLLO ORGANIZACIONAL6", "1234", "USUARIO", True, "ESTUDIOS Y DESARROLLO ORGANIZACIONAL-PROCESO DE SELECCIÓN (INTERNOS - EXTERNOS)"),
    ("ESTUDIOS Y DESARROLLO ORGANIZACIONAL5", "1234", "USUARIO", True, "ESTUDIOS Y DESARROLLO ORGANIZACIONAL-PROCESOS DE NORMALIZACIÓN"),
    ("ESTUDIOS Y DESARROLLO ORGANIZACIONAL4", "1234", "USUARIO", True, "ESTUDIOS Y DESARROLLO ORGANIZACIONAL-RECLUTAMIENTO DE FUNCIONARIOS TRANSITORIOS"),
    ("ESTUDIOS Y DESARROLLO ORGANIZACIONAL3", "1234", "USUARIO", True, "ESTUDIOS Y DESARROLLO ORGANIZACIONAL-CAMBIOS DE SERVICIO"),
    ("ESTUDIOS Y DESARROLLO ORGANIZACIONAL2", "1234", "USUARIO", True, "ESTUDIOS Y DESARROLLO ORGANIZACIONAL-CAPACITACIÓN"),
    ("ESTUDIOS Y DESARROLLO ORGANIZACIONAL1", "1234", "USUARIO", True, "ESTUDIOS Y DESARROLLO ORGANIZACIONAL-PERFILES DE CARGO"),
    ("CONCILIACION Y TRATO5", "1234", "USUARIO", True, "CONCILIACION Y TRATO-ATENCIONES INDIVIDUALES"),
    ("CONCILIACION Y TRATO4", "1234", "USUARIO", True, "CONCILIACION Y TRATO-ATENCIONES GRUPALES"),
    ("CONCILIACION Y TRATO3", "1234", "USUARIO", True, "CONCILIACION Y TRATO-MEDIACIONES"),
    ("CONCILIACION Y TRATO2", "1234", "USUARIO", True, "CONCILIACION Y TRATO-CONCILIACIONES"),
    ("CONCILIACION Y TRATO1", "1234", "USUARIO", True, "CONCILIACION Y TRATO-REUNIONES DE COORDINACIÓN"),
    ("REMUNERACIONES6", "1234", "USUARIO", True, "REMUNERACIONES-LIQUIDACIONES DE SUELDO"),
    ("REMUNERACIONES5", "1234", "USUARIO", True, "REMUNERACIONES-REMUNERACIONES"),
    ("REMUNERACIONES4", "1234", "USUARIO", True, "REMUNERACIONES-HORAS EXTRAORDONARIAS"),
    ("REMUNERACIONES3", "1234", "USUARIO", True, "REMUNERACIONES-REINTEGROS"),
    ("REMUNERACIONES2", "1234", "USUARIO", True, "REMUNERACIONES-RETENCIONES JUDICIALES"),
    ("REMUNERACIONES1", "1234", "USUARIO", True, "REMUNERACIONES-PARTICIPACIÓN GREMIAL"),
    ("HIGIENE Y SEGURIDAD1", "1234", "USUARIO", True, "HIGIENE Y SEGURIDAD-TRABAJO PESADO"),
    ("HIGIENE Y SEGURIDAD2", "1234", "USUARIO", True, "HIGIENE Y SEGURIDAD-SIMULACROS"),
    ("HIGIENE Y SEGURIDAD3", "1234", "USUARIO", True, "HIGIENE Y SEGURIDAD-TASAS"),
    ("HIGIENE Y SEGURIDAD4", "1234", "USUARIO", True, "HIGIENE Y SEGURIDAD-ENFERMEDADES PROFESIONALES"),
    ("HIGIENE Y SEGURIDAD5", "1234", "USUARIO", True, "HIGIENE Y SEGURIDAD-REGLAMENTO INTERNO"),
    ("HIGIENE Y SEGURIDAD6", "1234", "USUARIO", True, "HIGIENE Y SEGURIDAD-FORMULARIOS DE AGRESIÓN A FUNCIONARIOS"),
    ("HIGIENE Y SEGURIDAD7", "1234", "USUARIO", True, "HIGIENE Y SEGURIDAD-TRASTORNOS MUSCULOESQUELÉTICOS RELACIONADOS AL TRABAJO"),
    ("HIGIENE Y SEGURIDAD8", "1234", "USUARIO", True, "HIGIENE Y SEGURIDAD-CEAL -  SM"),
    ("HIGIENE Y SEGURIDAD9", "1234", "USUARIO", True, "HIGIENE Y SEGURIDAD-COGRID"),
    ("CONTROL DE PERSONAS6", "1234", "USUARIO", True, "CONTROL DE PERSONAS-DOTACIÓN AUTORIZADAS RESOLUCIÓN DE PRESUPUESTO DEL SSVQ 2025"),
    ("CONTROL DE PERSONAS5", "1234", "USUARIO", True, "CONTROL DE PERSONAS-DOTACIÓN EFECTIVA"),
    ("CONTROL DE PERSONAS4", "1234", "USUARIO", True, "CONTROL DE PERSONAS-RESPALDOS POR BRECHA"),
    ("CONTROL DE PERSONAS3", "1234", "USUARIO", True, "CONTROL DE PERSONAS-RESPALDOS POR FUEROS MATERNALES"),
    ("CONTROL DE PERSONAS2", "1234", "USUARIO", True, "CONTROL DE PERSONAS-SOLICITUDES DE TRANSPARENCIAS SUBDIRECCIÓN"),
    ("CONTROL DE PERSONAS1", "1234", "USUARIO", True, "CONTROL DE PERSONAS-RECLAMOS POR VULNERACIÓN DE DERECHOS PRESENTADOS  A LA CONTRALORÍA, POR TEMAS RELACIONADOS  GESTIÓN DE PERSONAS"),
]

with app.app_context():
    creados = 0
    for usuario, password, rol, activo, nombre_unidad in usuarios:
        unidad = Unidad.query.filter_by(nombre=nombre_unidad.strip()).first()
        if not unidad:
            print(f"Unidad no encontrada para usuario {usuario}: {nombre_unidad}")
            continue
        # Evita duplicados
        if not Usuario.query.filter_by(usuario=usuario).first():
            nuevo = Usuario(
                usuario=usuario.strip(),
                password=password.strip(),
                rol=rol.strip().lower(),  # Si tu modelo usa 'usuario', 'admin', etc.
                activo=activo,
                unidad_id=unidad.id
            )
            db.session.add(nuevo)
            creados += 1
    db.session.commit()
    print(f"Usuarios creados: {creados}")
